name: Agent Builder Tests

on:
  workflow_run:
    workflows: ['Quality assurance']
    types:
      - completed

jobs:
  check-changes:
    if: ${{ github.repository == 'mastra-ai/mastra' }}
    runs-on: ubuntu-latest
    outputs:
      agent-builder-changed: ${{ steps.changes.outputs.agent-builder }}
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set pending status
        uses: ./.github/workflows/shared-actions/set-pr-status
        with:
          status: 'pending'
          context: 'Agent Builder Tests'
          description: 'Checking for changes'
          sha: ${{ github.event.workflow_run.head_sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Check for agent-builder package changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          base: main
          ref: ${{ github.event.workflow_run.head_sha }}
          filters: |
            agent-builder:
              - 'packages/agent-builder/**'

  skip-tests:
    needs: check-changes
    if: needs.check-changes.outputs.agent-builder-changed == 'false'
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Set success status for unchanged agent-builder
        uses: ./.github/workflows/shared-actions/set-pr-status
        with:
          status: 'success'
          context: 'Agent Builder Tests'
          description: 'Agent Builder package unchanged - skipping tests'
          sha: ${{ github.event.workflow_run.head_sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  test:
    needs: check-changes
    if: ${{ github.repository == 'mastra-ai/mastra' && needs.check-changes.outputs.agent-builder-changed == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_CACHE: remote:r
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Configure npm registry
        run: mkdir -p ~/setup-pnpm && echo "registry=https://registry.yarnpkg.com" > ~/setup-pnpm/.npmrc

      - uses: wardpeet/action-setup@pnpm-registry
        name: Install pnpm
        with:
          registry: https://registry.yarnpkg.com
          run_install: false

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.1
          cache: 'pnpm'
          registry-url: 'https://registry.yarnpkg.com'

      - name: Install dependencies
        run: pnpm install

      - name: Build dependencies
        run: pnpm turbo build --filter "@mastra/agent-builder^..." --filter "./stores/*"

      - name: Run Agent Builder unit tests
        run: pnpm --filter "@mastra/agent-builder" test
        env:
          NODE_OPTIONS: '--max_old_space_size=8096'

      - name: Run Agent Builder integration tests
        run: pnpm --filter "@mastra/agent-builder-integration-tests" test
        env:
          NODE_OPTIONS: '--max_old_space_size=8096'
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  test-success:
    needs: [check-changes, test]
    if: ${{ always() && needs.check-changes.outputs.agent-builder-changed == 'true' && needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Set success status for completed tests
        uses: ./.github/workflows/shared-actions/set-pr-status
        with:
          status: 'success'
          context: 'Agent Builder Tests'
          description: 'All agent builder tests passed'
          sha: ${{ github.event.workflow_run.head_sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  test-failure:
    needs: [check-changes, test]
    if: ${{ always() && needs.check-changes.outputs.agent-builder-changed == 'true' && needs.test.result == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Set failure status for failed tests
        uses: ./.github/workflows/shared-actions/set-pr-status
        with:
          status: 'failure'
          context: 'Agent Builder Tests'
          description: 'Agent builder tests failed'
          sha: ${{ github.event.workflow_run.head_sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
