name: Schema Tests

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/schema-compat/**'
      - '.github/workflows/test-schema.yml'

jobs:
  test:
    # Only run on the main repository, not on forks
    if: ${{ github.repository == 'mastra-ai/mastra' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure npm registry
        run: mkdir -p ~/setup-pnpm && echo "registry=https://registry.yarnpkg.com" > ~/setup-pnpm/.npmrc

      - uses: wardpeet/action-setup@pnpm-registry
        name: Install pnpm
        with:
          registry: https://registry.yarnpkg.com
          run_install: false

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.1
          cache: 'pnpm'
          registry-url: 'https://registry.yarnpkg.com'

      - name: Install dependencies
        run: pnpm install

      - name: Build @mastra/schema-compat
        run: pnpm turbo --filter="./packages/schema-compat" build

      - name: Run Schema tests
        run: pnpm run test:schema-compat
