name: Client JS Tests

on:
  pull_request:
    branches: [main]
    paths:
      - 'client-sdks/client-js/**'
      - 'packages/core/**'
      - 'packages/server/**'
      - 'packages/deployer/**'
      - '.github/workflows/test-client-js.yml'

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    # Only run on the main repository, not on forks
    if: ${{ github.repository == 'mastra-ai/mastra' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure npm registry
        run: mkdir -p ~/setup-pnpm && echo "registry=https://registry.yarnpkg.com" > ~/setup-pnpm/.npmrc

      - uses: wardpeet/action-setup@pnpm-registry
        name: Install pnpm
        with:
          registry: https://registry.yarnpkg.com
          run_install: false

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.1
          cache: 'pnpm'
          registry-url: 'https://registry.yarnpkg.com'

      - name: Install dependencies
        run: pnpm install

      - name: Build core dependencies
        run: pnpm turbo build --filter "@mastra/core" --filter "@mastra/server" --filter "@mastra/deployer" --filter "mastra"

      - name: Run Client JS tests
        run: pnpm --filter "@mastra/client-js" test
        env:
          NODE_OPTIONS: '--max_old_space_size=8096'
